packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # import to reference voby from demo projects
  - 'demo/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
